name: excavator
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
permissions:
  contents: write
jobs:
  excavate:
    runs-on: windows-latest
    steps:
      - uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: '1'
